#!bin/bash

#  Docker start script for the AppDynamics Standalone Machine Agent
# In this example, APPD_* environment variables are passed to the container at runtime
MA_PROPERTIES="-Dappdynamics.controller.hostName=${APPD_HOST}"
MA_PROPERTIES+=" -Dappdynamics.controller.port=${APPD_PORT}"
MA_PROPERTIES+=" -Dappdynamics.agent.accountName=${APPD_ACCOUNT_NAME%%_*}" 
MA_PROPERTIES+=" -Dappdynamics.agent.accountAccessKey=${APPD_ACCESS_KEY}" 
MA_PROPERTIES+=" -Dappdynamics.controller.ssl.enabled=${APPD_SSL_ENABLED}"

# Optional Param - Enable SIM 
MA_PROPERTIES+=" -Dappdynamics.sim.enabled=true"

# Optional Param -  Enable docker visibility 
MA_PROPERTIES+=" -Dappdynamics.docker.enabled=true"

# Start Machine Agent
${MACHINE_AGENT_HOME}/jre/bin/java ${MA_PROPERTIES} -jar ${MACHINE_AGENT_HOME}/machineagent.jar
